### ISSUE TITLE
incompatible with current dev branch

### ISSUE THREAD

**Issue by w-e-w** [bit9labs/sd-masonry#1]
well some feedback as you requested https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/12225

I did a quick test and found that your extension is not compatible with current dev branch https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/541ef9247cfe8785c12f7142ad02cd5310fc5925
the web UI server back in successfully launched but the front end web page wasn't able to load and hangs when your extension is installed
a possible cause is that we switch to gradio 3.39

>lol, just realized you're you're the author of [sd-ratio-lock](https://github.com/bit9labs/sd-ratio-lock) 
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/164

**Comment by bit9labs** [comment]
What version of gradio is the master branch? I'll look into the changes. How often does dev get merged into master?

**Comment by w-e-w** [comment]
>What version of gradio is the master branch

irrc 3.32

>How often does dev get merged into master?]

it's not really a question of "often" it's, the question is "when"

we currently don't have a timeline for 1.6.0, due to some performance issues with 3.39 also has been considering reverting back to 3.32 but currently we are still using 3.39

if you want more updated news it's better for you to just join in auto Discord (link is on the wiki contributions page)

**Comment by w-e-w** [comment]
```
catboxanon — 2023/08/15 15:55
I was thinking we might want to wait until https://github.com/gradio-app/gradio/issues/4841 is fixed too before making an RC
https://github.com/gradio-app/gradio/pull/5215 this fixes most of the issues I believe so it would probably be part of the next Gradio version
AUTOMATIC — 2023/08/15 16:02
I'm not in a rush to make an RC
the list is going to have to be made anyway, and it can extended later
i think it was you that wrote a message about wanting RC
catboxanon — 2023/08/15 16:04
Yeah don't mean to rush at all
AUTOMATIC — 2023/08/15 16:05
if gradio doesn't fix performance soon, an option is just to revert to the previous version
we'd lose inpainting mask color and favicon is all
```

**Comment by bit9labs** [comment]
Well they forced my hand with the update this morning that merged the next release candidate into master. I've pushed updates to work with the latest.

**Comment by w-e-w** [comment]
ahhh... okay I guess, thank you for your work?
I don't think this should come as a surprise right
I did warn you about the issue and 1.6.0 has been in RC for the past week

**Comment by w-e-w** [comment]
if you want you can detect the webui version and then do different things based on the result

if you want to do so I could throw together a quick PR

**Comment by bit9labs** [comment]
Haha I'm not complaining. I was just being lazy. That would be great. It should be backwards compatible.

I was using the HTML element to detect when I need to trigger my JS change hooks, but there is some issue with the latest gradio that constantly calls the change handler for an HTML element even when that element isn't active or visible or changing. So it was essentially running a DoS attack on itself. I just had to duplicate my _js trigger in multiple places instead of one.

**Comment by w-e-w** [comment]
> I was just being lazy

lol
who isn't

**Comment by w-e-w** [comment]
a simple way to test webui verison if >= 1.6.0 return True
adapt it to your needs
```py
from pkg_resources import parse_version
import re


def if_webui_version_greater_or_equal_1_6_0():
    try:
        from launch import git_tag
        match = re.search(r'(\d+(?:\.\d)+)', git_tag())
        return bool(match and parse_version(match.group()) >= parse_version("1.6.0"))
    except:
        return False


if __name__ == '__main__':
    print(if_webui_version_greater_or_equal_1_6_0())
```

**Comment by w-e-w** [comment]
@bit9labs 
oh I almost forgot
when I asked you about listing your extension on index you said you want time to have feedback

well ...... you will get more feedback if you put it on index

when and if you're ready to have it listed jsut open a PR at https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions
> I could do it for you if you really want to but I prefer you to send over a PR so you can write your own descriptions
